### ISSUE TITLE
Aren't Symbol and Object.assing part of ES6?

### ISSUE THREAD

**Issue by gabrielperales** [mheiber/redux-machine#3]
I don't want to bother you, but they seems to be part of ES6 [MDN Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) [MDN Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures).
Also I have checked that `Object.assign` and `Symbol` are widely supported on current browsers. Check it [here](http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign) and [here](http://kangax.github.io/compat-table/es6/#test-Symbol).  They are not only supported by IE < 12 and Safary < 9, so that is cool 👍

**Comment by mheiber** [comment]
@gabrielperales you're absolutely right. "ES2015" and "ES6" are the same thing.
While I personally am tempted to think that users of old browsers should just be forced to upgrade (no one complained much about upgrading Flash!), there are plenty of companies and devs who have to support pre-IE12 users.

So it's nice to let the devs know they might want to use polyfills. If you don't need to support pre-IE-12, then you're lucky and don't need to include the polyfill.

**Comment by gabrielperales** [comment]
Yeah, I know. I told that because I saw the comment on the second commit "ES5 syntax so don't have to transpile". I also I thought that in the readme you were telling that they were part of ES5, but I misread it, it is clear that it says they are ES2015.
