### ISSUE TITLE
Unexpected token 'const' in PhantomJS (on KarmaJS)

### ISSUE THREAD

**Issue by realb0t** [mheiber/redux-machine#6]
Hello! It's beautiful lib, but I can't use it with Karma (and Webpack).
I gave error "Unexpected token 'const'" in my tests.

I think this is due PhantomJS because this error throw only in tests and I can't see it in build for browser (Chrome).

I could offer to replace "const" by "var" statement or rewrite on ES2015 (state-3) for babel build.
I can help if it need.

**Comment by mheiber** [comment]
@realb0t really glad you like the library!
The `const` stuff is just in the tests, the file with the library code (`index.js`) is written with ES5 syntax. Can you configure your test runner to ignore `node_modules`?

**Comment by realb0t** [comment]
Yes, I can ignore this library in tests. Thanks.

**Comment by 24min** [comment]
i h

> Yes, I can ignore this library in tests. Thanks.

how can i ignore some library in tests?
